-- Create App User
CREATE USER INVENTORY IDENTIFIED BY dbz;
GRANT CONNECT TO INVENTORY;
GRANT DBA TO INVENTORY;

CREATE TABLE inventory.customers (
    id VARCHAR2(255)  NOT NULL PRIMARY KEY,
    first_name VARCHAR2(255) NOT NULL,
    last_name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE,
    ett_date TIMESTAMP NULL
);

exit;

